import React from 'react';
import { 
  FileText, 
  Briefcase, 
  CheckCircle, 
  AlertTriangle, 
  Wand2, 
  ArrowRight, 
  Upload, 
  Download, 
  Layout, 
  Star,
  Zap,
  RefreshCw,
  Home,
  Info,
  Menu,
  X,
  ChevronDown,
  ChevronUp,
  Target,
  Brain,
  History,
  BookOpen,
  Lightbulb
} from 'lucide-react';

export const Icons = {
  Resume: FileText,
  Job: Briefcase,
  Check: CheckCircle,
  Alert: AlertTriangle,
  Magic: Wand2,
  ArrowRight: ArrowRight,
  Upload: Upload,
  Download: Download,
  Layout: Layout,
  Star: Star,
  Zap: Zap,
  Refresh: RefreshCw,
  Home: Home,
  Info: Info,
  Menu: Menu,
  Close: X,
  Down: ChevronDown,
  Up: ChevronUp,
  Target: Target,
  Brain: Brain,
  History: History,
  Meaning: BookOpen,
  Memory: Lightbulb
};